@echo off
echo Checking for existing dev server on port 5173...
for /f "tokens=5" %%a in ('netstat -ano ^| findstr :5173 ^| findstr LISTENING') do (
    echo Killing process %%a on port 5173...
    taskkill /F /PID %%a 2>nul
)
echo Starting dev server...
npm run dev:unsafe
